### ISSUE TITLE
frontend.py throwing error.

### ISSUE THREAD

**Issue by jageshmaharjan** [gnes-ai/demo-gnes-flow#3]
`attribute error: module 'grpc' has no attribute 'server'` throwing from frontend.py at gnes/service.
 my grpc version is 1.27.2
```
import grpc
>>> print(grpc.__version__)
1.27.2
```
I supposed in `frontend.py` at line 
insted of `grpc.server(...)` should have been `grpc.Server(...)`

However, fixing that threw another error:
```
~/anaconda3/envs/myenv/lib/python3.6/site-packages/gnes/service/frontend.py in __init__(self, args)
     21             ThreadPoolExecutor(max_workers=args.max_concurrency),
     22             options=[('grpc.max_send_message_length', args.max_message_size),
---> 23                      ('grpc.max_receive_message_length', args.max_message_size)])
     24         self.logger.info('start a frontend with %d workers' % args.max_concurrency)
     25         gnes_pb2_grpc.add_GnesRPCServicer_to_server(self._Servicer(args), self.server)

TypeError: object() takes no parameters
```

**Comment by jageshmaharjan** [comment]
Noticed that it work on grpc version 1.22.0 or lower.
`pip install grpcio==1.22.0`
